name: pagan_lab_001550
channels:
  - conda-forge
dependencies:
  - python==3.12
  - ipywidgets
  - pip
  - pip:
    - dandi
    - jupyter
    - h5py
    - remfile
    - pynwb
    - numpy
    - pandas
    - matplotlib
    - networkx
    - ndx-structured-behavior @ git+https://github.com/rly/ndx-structured-behavior.git@b31692480fa8c7e005dea7d843528582c02ef7e2
    - ndx-optogenetics==0.3.0
