name: ibl-widefield-demo
channels:
    - conda-forge
dependencies:
    - python==3.13
    - ipywidgets
    - pip
    - pip:
          - dandi
          - jupyter
          - matplotlib
          - pynwb
          - remfile
          - plotly
          - ibllib
