name: 001828_demo
channels:
    - conda-forge
dependencies:
    - python==3.11
    - pip
    - pip:
      - dandi
      - jupyter
      - matplotlib
      - numpy
      - pandas
      - pynwb
      - remfile
      - h5py
      - nwb-video-widgets
