# run: conda env create --file environment.yml
name: jadhav_notebook_env
channels:
    - conda-forge
dependencies:
    - python==3.12
    - ipykernel
    - matplotlib
    - dandi
    - pip
    - pip:
      - remfile
      - jadhav-lab-to-nwb @ git+https://github.com/catalystneuro/jadhav-lab-to-nwb.git@main